/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design tokens verbatim from src/Home.html <script id="tailwind-config">
        // so Home.js renders pixel-identical to Home.html.
        'on-secondary-fixed-variant': '#2e4f00',
        'on-secondary-fixed': '#102000',
        'surface-container': '#edeeef',
        'error-container': '#ffdad6',
        'on-primary-container': '#cad3ff',
        'on-primary-fixed': '#001551',
        'on-primary-fixed-variant': '#0039b5',
        'surface-container-high': '#e7e8e9',
        'tertiary-container': '#515c70',
        'on-error-container': '#93000a',
        'surface-bright': '#f8f9fa',
        'surface-tint': '#2151da',
        secondary: '#3f6900',
        'outline-variant': '#c4c5d7',
        'inverse-on-surface': '#f0f1f2',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#b7c4ff',
        outline: '#747686',
        'on-background': '#191c1d',
        surface: '#f8f9fa',
        'on-tertiary-fixed': '#111c2d',
        'primary-container': '#1d4ed8',
        'tertiary-fixed': '#d8e3fb',
        'on-secondary-container': '#437000',
        'on-primary': '#ffffff',
        'inverse-primary': '#b7c4ff',
        primary: '#0037b0',
        'on-tertiary-fixed-variant': '#3c475a',
        'primary-fixed': '#dce1ff',
        'secondary-container': '#aff75a',
        'secondary-fixed': '#aff75a',
        'surface-variant': '#e1e3e4',
        'on-tertiary': '#ffffff',
        tertiary: '#3a4558',
        'surface-container-highest': '#e1e3e4',
        'surface-dim': '#d9dadb',
        background: '#f8f9fa',
        'on-surface-variant': '#434655',
        'surface-container-low': '#f3f4f5',
        'on-tertiary-container': '#c9d5ed',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#bcc7de',
        'on-surface': '#191c1d',
        'on-secondary': '#ffffff',
        error: '#ba1a1a',
        'inverse-surface': '#2e3132',
        'secondary-fixed-dim': '#95da40',
        // Design tokens verbatim from src/Details.html <script id="tailwind-config">
        // (additive only — pre-existing Home.js tokens above are preserved).
        // Details.html uses default Tailwind palettes (slate/blue/lime) plus
        // these brand/surface aliases; kept here so Details.js matches the
        // HTML CDN build pixel-for-pixel.
        brand: {
          blue: '#1d4ed8',
          'blue-dark': '#0037b0',
          'blue-light': '#3b82f6',
          lime: '#84cc16',
          'lime-dark': '#65a30d',
          'lime-light': '#ecfccb',
        },
      },
      boxShadow: {
        // Verbatim from Details.html tailwind.config.extend.boxShadow
        soft: '0 8px 30px rgba(15, 23, 42, 0.05)',
        float: '0 14px 40px rgba(29, 78, 216, 0.12)',
        subtle: '0 2px 10px rgba(0, 0, 0, 0.03)',
        xs: '0 1px 2px rgba(15, 23, 42, 0.06)',
        '2xs': '0 1px 2px rgba(15, 23, 42, 0.04)',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
        // Verbatim from Details.html tailwind.config.extend.borderRadius
        card: '1.75rem',
        pill: '9999px',
      },
      spacing: {
        'space-md': '1rem',
        margin: '2.5rem',
        'space-xs': '0.25rem',
        'space-lg': '1.5rem',
        'space-sm': '0.5rem',
        gutter: '1.5rem',
        'margin-mobile': '1rem',
        'gutter-mobile': '1rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        'headline-sm': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'body-sm': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
        'body-xl': ['Plus Jakarta Sans'],
        'headline-xl': ['Plus Jakarta Sans'],
        'display-hero': ['Plus Jakarta Sans'],
        'headline-xl-mobile': ['Plus Jakarta Sans'],
        'display-hero-mobile': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'label-lg': ['Plus Jakarta Sans'],
        // Kept for pre-existing components (e.g. SubmissionForm uses Inter body):
        'body-lg': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '700' }],
        'body-xl': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-xl': ['44px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-hero': ['60px', { lineHeight: '68px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-xl-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-hero-mobile': ['38px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-lg': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
